repos:
  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
        args: [--in-place]
#  - repo: https://github.com/pycqa/flake8
#    rev: 7.3.0
#    hooks:
#      - id: flake8
#        args: [--max-line-length=100, --ignore=E203,W503,F401,F841]